language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.10"
install:
  - "cpanm --quiet --installdeps --notest RDF::LinkedData"
  - "cpanm --quiet --installdeps --notest Module::Package::RDF"

